apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sfr
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Philip95/fhtsfr.git
    targetRevision: HEAD
    path: deployment
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
